# Generated by Django 4.1.7 on 2023-03-24 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transferguideapp', '0004_alter_favorites_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorites',
            old_name='course',
            new_name='in_course',
        ),
        migrations.AddField(
            model_name='favorites',
            name='ex_course',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='transferguideapp.externalcourse'),
            preserve_default=False,
        ),
    ]
