# Generated by Django 4.1.6 on 2023-03-27 04:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transferguideapp', '0005_rename_course_favorites_in_course_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorites',
            name='ex_course',
        ),
        migrations.RemoveField(
            model_name='favorites',
            name='in_course',
        ),
        migrations.AddField(
            model_name='favorites',
            name='transfer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='transferguideapp.coursetransfer'),
        ),
        migrations.AlterField(
            model_name='favorites',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='favorite_items', to=settings.AUTH_USER_MODEL),
        ),
    ]
