# Generated by Django 4.1.6 on 2023-04-07 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transferguideapp', '0010_transferrequest_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferrequest',
            name='response',
            field=models.CharField(default='', max_length=200),
        ),
    ]
