# Generated by Django 4.1.7 on 2023-04-11 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transferguideapp', '0012_internalcourse_credits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internalcourse',
            name='credits',
            field=models.CharField(default=-1, max_length=30),
        ),
    ]
