# Generated by Django 4.1.7 on 2023-04-11 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transferguideapp', '0013_alter_internalcourse_credits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internalcourse',
            name='credits',
        ),
    ]
