# Generated by Django 4.1.6 on 2023-04-30 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transferguideapp', '0017_adminkey'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalcourse',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
