# Generated by Django 4.1.6 on 2023-04-30 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transferguideapp', '0018_externalcourse_hidden'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='externalcourse',
            name='hidden',
        ),
        migrations.AddField(
            model_name='externalcourse',
            name='admin',
            field=models.BooleanField(default=True),
        ),
    ]
